# Generated by Django 3.0.5 on 2020-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('investment', models.FloatField(default=0.0)),
                ('share', models.FloatField(default=0.0)),
                ('worth', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
            ],
        ),
    ]
