# Generated by Django 3.0.5 on 2020-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='created_time',
            field=models.DateField(),
        ),
    ]
